### ISSUE TITLE
Upgrade OpenAI Python library

### ISSUE THREAD

**Issue by jhyearsley** [stanfordnlp/dspy#258] opened 2023-12-26 07:01 UTC
DSPy is using `openai<=0.28.1` and current version of OpenAI python library is `1.6.1`. There are breaking changes and with the rapid pace of development I think we should try and catch up to the latest version sooner rather than later. See the [v1.0.0 Migration Guide](https://github.com/openai/openai-python/discussions/742)

**Comment by okhat** [comment] 2023-12-26 14:31
Hey @jhyearsley , OK I agree. But this will be a new class `dspy.OpenAI_v1` with something like `pip install dspy-ai[openai_v1]`, is that fine?

We need to continue supporting the old version.

**Comment by jhyearsley** [comment] 2023-12-26 17:34
Yeah makes sense. Curious to learn more about what is depending on the older version though. Are there dependencies that would break even with a staged refactor that preserves backwards compatibility?

**Comment by okhat** [comment] 2023-12-26 17:43
Hey @jhyearsley merged to main.

Requirements still point to 0.28 but if you just do `pip install openai --upgrade`, it'll work with 1.0 or more recent just fine.

The old caches and the new caches are disjoint. e.g., rerunning the intro notebook with 1.0 will require an API key

**Comment by okhat** [comment] 2023-12-26 17:43
Thanks to @DanielUH2019 for most of this change

**Comment by jhyearsley** [comment] 2023-12-26 17:58
Awesome!

**Comment by okhat** [comment] 2023-12-26 18:25
This is on `main` now but not yet on pypi. Won't push to pypi until I get 1-2 confirmations it works fine for people.

**Comment by jhyearsley** [comment] 2023-12-26 18:31
Ok, good point, maybe better to keep open then until it is pushed to pypi

**Comment by dkshjn** [comment] 2023-12-28 20:20
I encountered an issue while using the latest update of the `dspy` package. Below are the details of my environment and the problem:
```
OS: macOS 14.2
Python Version: 3.10.12
OpenAI Version: 1.6.1
```
dspy Version: Installed using git.
```Python
!pip install git+https://github.com/stanfordnlp/dspy.git
```

Using the BasicQA class I asked a simple question but was facing an error.
```Python
class BasicQA(dspy.Signature):
    """Answer questions with short factoid answers."""

    question = dspy.InputField()
    answer = dspy.OutputField(desc="often between 1 and 5 words")

generate_answer = dspy.Predict(BasicQA)
example = "Hello, how are you?"
pred = generate_answer(question=example)
print(f"Question: {example}")
print(f"Predicted Answer: {pred.answer}")
```
**Error Message**
```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
[<ipython-input-30-9298526c36ff>](https://localhost:8080/#) in <cell line: 3>()
      1 generate_answer = dspy.Predict(BasicQA)
      2 dev_example='Hello how are you?'
----> 3 pred = generate_answer(question=dev_example)
      4 print(f"Question: {dev_example}")
      5 print(f"Predicted Answer: {pred.answer}")

18 frames
[/usr/local/lib/python3.10/dist-packages/dspy/predict/predict.py](https://localhost:8080/#) in __call__(self, **kwargs)
     58 
     59     def __call__(self, **kwargs):
---> 60         return self.forward(**kwargs)
     61 
     62     def forward(self, **kwargs):

[/usr/local/lib/python3.10/dist-packages/dspy/predict/predict.py](https://localhost:8080/#) in forward(self, **kwargs)
     85 
     86         if self.lm is None:
---> 87             x, C = dsp.generate(signature, **config)(x, stage=self.stage)
     88         else:
     89             with dsp.settings.context(lm=self.lm, query_only=True):

[/usr/local/lib/python3.10/dist-packages/dsp/primitives/predict.py](https://localhost:8080/#) in do_generate(example, stage, max_depth, original_example)
     76         # Generate and extract the fields.
     77         prompt = template(example)
---> 78         completions: list[dict[str, Any]] = generator(prompt, **kwargs)
     79         completions: list[Example] = [template.extract(example, p) for p in completions]
     80 

[/usr/local/lib/python3.10/dist-packages/dsp/modules/gpt3.py](https://localhost:8080/#) in __call__(self, prompt, only_completed, return_sorted, **kwargs)
    165         #         kwargs = {**kwargs, "logprobs": 5}
    166 
--> 167         response = self.request(prompt, **kwargs)
    168 
    169         choices = response["choices"]

[/usr/local/lib/python3.10/dist-packages/backoff/_sync.py](https://localhost:8080/#) in retry(*args, **kwargs)
    103 
    104             try:
--> 105                 ret = target(*args, **kwargs)
    106             except exception as e:
    107                 max_tries_exceeded = (tries == max_tries_value)

[/usr/local/lib/python3.10/dist-packages/dsp/modules/gpt3.py](https://localhost:8080/#) in request(self, prompt, **kwargs)
    131             del kwargs["model_type"]
    132 
--> 133         return self.basic_request(prompt, **kwargs)
    134 
    135     def _get_choice_text(self, choice: dict[str, Any]) -> str:

[/usr/local/lib/python3.10/dist-packages/dsp/modules/gpt3.py](https://localhost:8080/#) in basic_request(self, prompt, **kwargs)
    108         else:
    109             kwargs["prompt"] = prompt
--> 110             response = completions_request(**kwargs)
    111 
    112         history = {

[/usr/local/lib/python3.10/dist-packages/dsp/modules/gpt3.py](https://localhost:8080/#) in completions_request(**kwargs)
    250         return cached_gpt3_request_v2_wrapped(**kwargs)
    251 
--> 252     return v1_cached_gpt3_request_v2_wrapped(**kwargs).model_dump()

[/usr/local/lib/python3.10/dist-packages/dsp/modules/cache_utils.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
     15         @wraps(func)
     16         def wrapper(*args, **kwargs):
---> 17             return func(*args, **kwargs)
     18 
     19         return wrapper

[/usr/local/lib/python3.10/dist-packages/dsp/modules/gpt3.py](https://localhost:8080/#) in v1_cached_gpt3_request_v2_wrapped(**kwargs)
    225 @NotebookCacheMemory.cache
    226 def v1_cached_gpt3_request_v2_wrapped(**kwargs):
--> 227     return v1_cached_gpt3_request_v2(**kwargs)
    228 
    229 @CacheMemory.cache

[/usr/local/lib/python3.10/dist-packages/joblib/memory.py](https://localhost:8080/#) in __call__(self, *args, **kwargs)
    653 
    654     def __call__(self, *args, **kwargs):
--> 655         return self._cached_call(args, kwargs)[0]
    656 
    657     def __getstate__(self):

[/usr/local/lib/python3.10/dist-packages/joblib/memory.py](https://localhost:8080/#) in _cached_call(self, args, kwargs, shelving)
    596 
    597         if must_call:
--> 598             out, metadata = self.call(*args, **kwargs)
    599             if self.mmap_mode is not None:
    600                 # Memmap the output at the first call to be consistent with

[/usr/local/lib/python3.10/dist-packages/joblib/memory.py](https://localhost:8080/#) in call(self, *args, **kwargs)
    854         if self._verbose > 0:
    855             print(format_call(self.func, args, kwargs))
--> 856         output = self.func(*args, **kwargs)
    857         self.store_backend.dump_item(
    858             [func_id, args_id], output, verbose=self._verbose)

[/usr/local/lib/python3.10/dist-packages/dsp/modules/gpt3.py](https://localhost:8080/#) in v1_cached_gpt3_request_v2(**kwargs)
    220 @CacheMemory.cache
    221 def v1_cached_gpt3_request_v2(**kwargs):
--> 222     return openai.completions.create(**kwargs)
    223 
    224 @functools.lru_cache(maxsize=None if cache_turn_on else 0)

/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py in wrapper(*args, **kwargs)

/usr/local/lib/python3.10/dist-packages/openai/resources/completions.py in create(self, model, prompt, best_of, echo, frequency_penalty, logit_bias, logprobs, max_tokens, n, presence_penalty, seed, stop, stream, suffix, temperature, top_p, user, extra_headers, extra_query, extra_body, timeout)

/usr/local/lib/python3.10/dist-packages/openai/_base_client.py in post(self, path, cast_to, body, options, files, stream, stream_cls)

/usr/local/lib/python3.10/dist-packages/openai/_base_client.py in request(self, cast_to, options, remaining_retries, stream, stream_cls)

/usr/local/lib/python3.10/dist-packages/openai/_base_client.py in _request(self, cast_to, options, remaining_retries, stream, stream_cls)

NotFoundError: <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" href="/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2" as="font" crossorigin="" type="font/woff2"/><link rel="stylesheet" href="/_next/static/css/d89023f99e61550c.css" data-precedence="next"/><link rel="preload" as="script" fetchPriority="low" href="/_next/static/chunks/webpack-09f5645cf2f48492.js"/><script src="/_next/static/chunks/3cb0033b-af6f2543dce1b5ea.js" async=""></script><script src="/_next/static/chunks/8e0537fe-683deeeb4f7240cb.js" async=""></script><script src="/_next/static/chunks/4235-83e586a0b75425d2.js" async=""></script><script src="/_next/static/chunks/main-app-5548cbf547bb8509.js" async=""></script><script src="/_next/static/chunks/b358ca60-6e6be5b21c53daff.js" async=""></script><script src="/_next/static/chunks/3439-88eb74d7140814ad.js" async=""></script><script src="/_next/static/chunks/6009-6ff594f997d3d42b.js" async=""></script><script src="/_next/static/chunks/308-bd5891b466f7da36.js" async=""></script><script src="/_next/static/chunks/3527-a52b8cb1b8efc256.js" async=""></script><script src="/_next/static/chunks/3875-963b9828b9b37189.js" async=""></script><script src="/_next/static/chunks/4049-b4712d18555b8624.js" async=""></script><script src="/_next/static/chunks/1387-98a24adf0c4456bf.js" async=""></script><script src="/_next/static/chunks/7342-acaaf397d1a80c17.js" async=""></...
```

Let me know if you need any further details or if I should create an issue.
Thanks.

**Comment by okhat** [comment] 2023-12-28 20:26
@dkshjn did things work before upgrading to openai 1? And are you using a standard openai key, or using azure(

**Comment by dkshjn** [comment] 2023-12-28 20:40
Previously I was facing an error as well so I hoped it would be resolved by this update. 
I am using the model OpenChat 3.5 from OpenRouter.

**Comment by sutyum** [comment] 2023-12-29 08:53
> Previously I was facing an error as well so I hoped it would be resolved by this update. I am using the model OpenChat 3.5 from OpenRouter.

It works fine with Openai keys. Changing the base url to use a different provider is currently causing this error

**Comment by okhat** [comment] 2023-12-29 14:28
Ah thank you @sutyum and @dkshjn. Good catch! I think I understand the issue, I’ll check

**Comment by okhat** [comment] 2023-12-29 14:28
Just to be sure how are you changing the base url now

**Comment by dkshjn** [comment] 2023-12-29 15:16
Using ```api_base``` as shown below.
```Python
model = dspy.OpenAI(model = 'model', api_base = 'url', api_key = 'api_key')
```

**Comment by okhat** [comment] 2023-12-29 20:25
@dkshjn Hmm I pushed a further change. If it doesn't work I wonder if the issue is limited support for the new API at the other provider somehow?

**Comment by sutyum** [comment] 2024-01-16 09:04
It seems that dspy-ai (2.1.1 and the HEAD of the repo) has reverted back from 0.28.1. Just wanted to bring to notice here.

**Comment by MikeRenwick-ICG** [comment] 2024-01-17 15:20
Why not use something like litellm and free yourselves from the tyranny of individual package upgrade paths?

**Comment by okhat** [comment] 2024-01-17 15:28
Yeah I’d love to outsource this. I asked someone to look into langchain-community as the source of LLMs. One issue is that it doesn’t natively support n > 1 completions easily.

does litellm have that?

@sutyum the head didn’t revert, you just need to update openai separately

**Comment by MikeRenwick-ICG** [comment] 2024-01-17 17:01
Yes I think so - they have decent docs too - keeping track of features supported across different LLMs https://docs.litellm.ai/docs/completion/input

**Comment by CommanderCrowCode** [comment] 2024-01-18 08:33
While OpenAI@latest dependency can be done as suggested by
1. Install DSPy with OpenAI=0.28
2. Upgrade OpenAI post DSPy installation

This old works if you use a certain method of dependency management like `pip`. Something like `poetry` will never allow you to skip dependency check in any case. I'd still advocate for this to be addressed. 

Would love to help if someone gives me a quick bullet point list of where I should start looking at.

**Comment by okhat** [comment] 2024-01-18 08:34
Hmm, I see. We can have dspy-ai[new-openai] maybe?

**Comment by CommanderCrowCode** [comment] 2024-01-18 09:20
> Hmm, I see. We can have dspy-ai[new-openai] maybe?

That should work really well!

**Comment by jhyearsley** [comment] 2024-01-18 09:44
I'd recommend going with a different naming convention e.g. `dspy-ai[openai_v1]` so that when (say) the API is upgraded to v2 the new name is `dspy-ai[openai-v2]` (as opposed to `dspy-ai[new-new-openai]` 😄)

Wasn't that the original idea from an [earlier comment](https://github.com/stanfordnlp/dspy/issues/258#issuecomment-1869583263) or did I misunderstand the issue?

**Comment by ameyitis** [comment] 2024-02-02 22:49
Any updates here, poetry won't work with this.

**Comment by DrChrisLevy** [comment] 2024-02-06 14:44
I also just tried installing dspy via `poetry add dspy-ai` into an existing project which depends on `openai (^1.1.1)` and datasets `(^2.15.0`). Both of these conflict. The datasets one is probably an easy fix. But yea having dspy support older/newer versions of openai maybe not as easy.

**Comment by kujenga** [comment] 2024-02-06 19:23
With https://github.com/stanfordnlp/dspy/pull/347 this library should now be installable for those using openai >1.0, though the version used in the lockfile for this repo is still the same.

**Comment by okhat** [comment] 2024-02-06 19:27
Yes but not on pypi yet

**Comment by okhat** [comment] 2024-02-06 19:27
Just on main

**Comment by DrChrisLevy** [comment] 2024-02-06 20:25
This is great Thanks!
I wonder if we should do the same with the datasets library (relax the version).
I just checked out the project and went through the contributing docs.
I tried pushing to a remote branch but access denied.

**Comment by okhat** [comment] 2024-02-07 20:44
EVERYONE, this is now resolved and pushed to pypi and seems all good.

We'll have to remember though that any cached notebooks will require explicit openai~=0.28.1 to work.

**Closed by okhat** 2024-02-07 20:44 UTC

**Comment by SimonB97** [comment] 2024-03-05 10:30
> EVERYONE, this is now resolved and pushed to pypi and seems all good.
> 
> We'll have to remember though that any cached notebooks will require explicit openai~=0.28.1 to work.

Thanks, though I struggled a bit till I found this issue and I think this should be stated more clearly (as long as it's not resolved fully), maybe right in the readme. Would've saved me some time figuring out what's wrong.
