### ISSUE TITLE
Reproducible results with HFModel or MLC

### ISSUE THREAD

**Issue by Sohaila-se** [stanfordnlp/dspy#140] opened 2023-09-24 10:52 UTC
I noticed that the results are not reproducible. I am using Llama with BootstrapFewShot, and every time I compile the same program, I get totally different results (not even close).
I noticed in the Predict forward function that the temperature is changed, so is there a way to set the temperature to 0 to be able to get reproducible results?

**Comment by okhat** [comment] 2023-09-24 10:56
Are you using llama through TGI client or through HFModel?

**Comment by okhat** [comment] 2023-09-24 10:59
If you use the TGI client, all results are reproducible. The HFModel is supported now only on a "best effort" basis. No promises that it's great yet.

**Comment by okhat** [comment] 2023-09-24 11:00
We have documentation for TGI here: https://github.com/stanfordnlp/dspy/blob/main/docs/language_models_client.md#tgi

**Comment by Sohaila-se** [comment] 2023-09-24 11:05
Well, thank you Omar.
I am actually using the MLC client following this tutorial docs/using_local_models.md

**Comment by okhat** [comment] 2023-09-24 11:10
Makes sense. HFModel and especially MLC are currently great for demos / exploration, but they're not going to be reliable for systematic tests. MLC in particular is quantized so a lot of noise could exist across runs.

TGI client (for open models) and OpenAI are resilient. (You can try to do compiled_program.save('path') and later load it. That's one option for reproducibility.)

Otherwise I've assigned this issue to myself to make these reproducible through caching. This is expected to take 1--2 weeks.

**Comment by Sohaila-se** [comment] 2023-09-24 13:41
I will give the TGI client a try.  Thank you @okhat.

**Comment by Sohaila-se** [comment] 2023-09-27 14:33
I was able to get reproducible results by setting the temperature of Llama to zero.

In hf_client.py I passed **kwargs to `ChatConfig`. 

```
class ChatModuleClient(HFModel):
    def __init__(self, model, model_path, **kwargs):
        super().__init__(model=model, is_client=True)

        from mlc_chat import ChatModule
        from mlc_chat import ChatConfig

        self.cm = ChatModule(model=model, lib_path=model_path, chat_config=ChatConfig(**kwargs))
```

```
kwarg = {
    "temperature": 0.0,
    "conv_template": "LM",
}

llama = dspy.ChatModuleClient(model='mlc-chat-Llama-2-7b-chat-hf-q4f16_1', 
                              model_path='dist/prebuilt/lib/Llama-2-7b-chat-hf-q4f16_1-cuda.so',
                              **kwarg)

dspy.settings.configure(lm=llama)
```

This can also be done by editing `mlc-chat-config.json`

**Comment by darinkishore** [comment] 2023-11-01 18:25
> Makes sense. HFModel and especially MLC are currently great for demos / exploration, but they're not going to be reliable for systematic tests. MLC in particular is quantized so a lot of noise could exist across runs.
> 
> TGI client (for open models) and OpenAI are resilient. (You can try to do compiled_program.save('path') and later load it. That's one option for reproducibility.)
> 
> Otherwise I've assigned this issue to myself to make these reproducible through caching. This is expected to take 1--2 weeks.

@okhat, quick question. I've started running dspy on my larger tasks. When I save the TGI pipeline (or even an openai one), the lm is set to none. Is this due to improper config on my part? 

```python
    lm = dspy.OpenAI(model=model_name, api_key=os.getenv('OPENAI_API_KEY'))
    dspy.settings.configure(lm=lm)
    if RECOMPILE_INTO_LLAMA_FROM_SCRATCH:
        tp = BootstrapFewShot(metric=metric_EM, max_bootstrapped_demos=2, max_rounds=1, max_labeled_demos=2)
        compiled_boostrap = tp.compile(DetectConcern(), trainset=train_examples[:10], valset=train_examples[-10:])
        print("woof")
        try:
            compiled_boostrap.save(os.path.join(ROOT_DIR, "dat", "college", f"{model_name}_concerndetect.json"))
```

outputs a json file after the pipeline with 
```json
{
  "most_likely_concerns": {
    "lm": null,
    "traces": [],
    "train": [],
    "demos": "omitted"
},
  "concern_present": {
    "lm": null,
    "traces": [],
    "train": [],
    "demos": "omitted"
},
```

I have identical output (in terms of LM field, traces, train) when saving a Llama-13b pipeline. Am I doing something obviously wrong, or is saving still inconsistent? My pipeline (don't think it would matter) is below for reference:

```python
class DetectConcern(dspy.Module):
    def __init__(self):
        super().__init__()
        self.most_likely_concerns = dspy.Predict(MostLikelyConcernsSignature, max_tokens=100)
        self.concern_present = dspy.ChainOfThought(ConcernPresentSignature)

    def forward(self, title, post, possible_concerns):
        # Get the most likely concerns
        most_likely_concerns = self.most_likely_concerns(
            title=title, post=post, possible_concerns=possible_concerns
        ).most_likely_concerns

        # Process the concerns
        cleaned_concerns = clean_concerns_to_list(most_likely_concerns)
        detected_concerns = []
        
        # for first six concerns, check if they are present in the post
        for clean_concern in cleaned_concerns[:6]:
            concern_present = self.concern_present(
                title=title, post=post, concern=clean_concern
            )
            is_concern_present = concern_present.concern_present
            reasoning = concern_present.reasoning
            if true_or_false(is_concern_present):
                detected_concerns.append(clean_concern)

        detected_concerns = ', '.join(detected_concerns)
        return detected_concerns
        ```

**Comment by okhat** [comment] 2023-11-01 19:33
@darinkishore 
LM=none is not a bug here. None just means use the current LM.

**Comment by darinkishore** [comment] 2023-11-01 22:17
Thank you for the prompt response!

I asked because I had some model save/load issues, but not 100% sure what code was causing this stack trace (forgot you can enable WANDB code saving), but I ran into it a lot last night. 

```python
 8   File "/local/scratch/dakisho/2_concern_search/./src/0_preprocess/dspy_tagging.py", line 389, in main
 9     pipeline, _ = compile_pipeline(model_name="llama-13b")
10                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11   File "/local/scratch/dakisho/2_concern_search/./src/0_preprocess/dspy_tagging.py", line 367, in compile_pipeline
12     compiled_boostrap = tp.compile(DetectConcern(), trainset=train_examples[:50], valset=train_examples[51:])
13                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14   File "/home/dakisho/.pyenv/versions/3.11.6/lib/python3.11/site-packages/dspy/teleprompt/bootstrap.py", line 51, in compile
15     self._bootstrap()
16   File "/home/dakisho/.pyenv/versions/3.11.6/lib/python3.11/site-packages/dspy/teleprompt/bootstrap.py", line 98, in _bootstrap
17     success = self._bootstrap_one_example(example, round_idx)
18               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19   File "/home/dakisho/.pyenv/versions/3.11.6/lib/python3.11/site-packages/dspy/teleprompt/bootstrap.py", line 146, in _bootstrap_one_example
20     raise e
21   File "/home/dakisho/.pyenv/versions/3.11.6/lib/python3.11/site-packages/dspy/teleprompt/bootstrap.py", line 124, in _bootstrap_one_example
22     lm = lm.copy(temperature=0.7 + 0.001 * round_idx) if round_idx > 0 else lm
23          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
24   File "/home/dakisho/.pyenv/versions/3.11.6/lib/python3.11/site-packages/dsp/modules/lm.py", line 89, in copy
25     model = kwargs.pop('model')
26             ^^^^^^^^^^^^^^^^^^^
```

I'll keep digging and see if I can produce a reproducible example. Know that's not very helpful.

**Comment by jashshah09** [comment] 2024-06-27 20:55
Hey, is there a way to pass temperature and other parameters while using HFModel()? I am trying to use dspy with deepseekcoder-v1.

**Closed** 2024-09-25 15:25 UTC
