### ISSUE TITLE
even if i am handling this case by using format attribute of dspy.OutputFeild() but still getting error.

### ISSUE THREAD

**Issue by anushka192001** [stanfordnlp/dspy#877] opened 2024-04-20 09:27 UTC
12 frames
[<ipython-input-51-3ca6cf79764f>](https://localhost:8080/#) in <lambda>(x)
      3 
      4     speech = dspy.InputField()
----> 5     extracted_tokens = dspy.OutputField(desc="extract words from text",format=lambda x: ' '.join(x) if isinstance(x, list) else str(x))

TypeError: sequence item 0: expected str instance, list found

**Comment by okhat** [comment] 2024-04-20 16:41
Hm that’s strange. Can you share a small example to replicate the error

**Comment by anushka192001** [comment] 2024-04-21 07:41
@okhat  leave i tackled it anyhow but now i am getting this new error "index out of bound in embedding layer" when i use more than 14 examples to train but when i decrease no. of examples then it works all fine. 

 i am using gpt2 from hugging face and small snipet of code is ....

#teleprompeter to optimize the weights of this program using a metric defined validate_Pred_Imp_words
from dspy.teleprompt import BootstrapFewShot,Ensemble

# Define the validation logic for the hate speech classification task
def validate_hate_speech(example, pred, trace=None):
    for  i in range(3):
     if i+1<=len(example.extracted_tokens):
      if not find_similarity(example.extracted_tokens[i],pred.pred_extracted_tokens[i]):
        return False
     if i+1<=len(example.label):
      if str(example.label[i]) != str(pred.pred_label[i]):
        return False
     if i+1<=len(example.target):
       if not find_similarity(example.target[i],pred.pred_target[i]):
        return False
    return True

# Set up the teleprompter
teleprompter = BootstrapFewShot(metric=validate_hate_speech)

# Compile the program
compiled_program = teleprompter.compile(HateSpeechClassifier(), trainset=extract_words_dataset_train[:14])

**Comment by arnavsinghvi11** [comment] 2024-04-27 23:25
Hi @anushka192001 , could you share the full error trace for this program? It's unclear what `"index out of range in self" ` refers to

**Comment by anushka192001** [comment] 2024-04-28 10:21
@arnavsinghvi11  can you please share your mail id i will share the code on which i am getting this error.

**Comment by anushka192001** [comment] 2024-04-28 10:22
@arnavsinghvi11  THE ERROR-----   

0%|          | 0/100 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (1037 > 1024). Running this sequence through the model will result in indexing errors
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Failed to run or to evaluate example Example({'speech': 'u really think i would not have been raped by feral hindu or muslim back in india or bangladesh and a neo nazi would rape me as well just to see me cry', 'extracted_tokens': [['raped', 'neo', 'nazi', 'would', 'rape'], ['raped', 'feral', 'hindu', 'muslim', 'neo', 'nazi']], 'label': ['0', '2', '2'], 'target': [['Hindu', 'Islam'], ['Hindu', 'Islam'], ['Hindu', 'Islam', 'Other']]}) (input_keys={'speech'}) with <function validate_hate_speech at 0x7eeb746a1090> due to index out of range in self.
Failed to run or to evaluate example Example({'speech': 'the uk has threatened to return radioactive waste to the eu if an agreement cannot be reached can not we keep the radioactive waste and send back all the paki migrants instead', 'extracted_tokens': [['paki', 'migrants'], ['paki'], ['send', 'back', 'all', 'the', 'paki', 'migrants', 'instead']], 'label': ['2', '2', '0'], 'target': [['Minority', 'Refugee', 'Indian'], ['Indian'], ['Refugee', 'Islam']]}) (input_keys={'speech'}) with <function validate_hate_speech at 0x7eeb746a1090> due to index out of range in self.

  3%|▎         | 3/100 [00:07<04:04,  2.53s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Failed to run or to evaluate example Example({'speech': 'if english is not imposition then hindi is also not imposition shut up chutiya retards stophindiimposition', 'extracted_tokens': [['chutiya', 'retards', 'stophindiimposition'], ['retards']], 'label': ['2', '2', '2'], 'target': [['Other'], ['Hindu'], ['Hindu', 'Other']]}) (input_keys={'speech'}) with <function validate_hate_speech at 0x7eeb746a1090> due to index out of range in self.

  4%|▍         | 4/100 [00:16<07:29,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 4/100 [00:16<06:43,  4.21s/it]Failed to run or to evaluate example Example({'speech': 'no liberal congratulated hindu refugees post cab because they hate hindus', 'extracted_tokens': [['hate', 'hindus'], ['hate', 'hindus']], 'label': ['2', '2', '2'], 'target': [['Hindu'], ['Hindu'], ['Hindu']]}) (input_keys={'speech'}) with <function validate_hate_speech at 0x7eeb746a1090> due to index out of range in self.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-33-3c0e7e71fcaa>](https://localhost:8080/#) in <cell line: 37>()
     35 
     36 # Compile the program
---> 37 compiled_program = teleprompter.compile(HateSpeechClassifier(), trainset=extract_words_dataset_train[:100])



25 frames

[/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   2235         # remove once script supports set_grad_enabled
   2236         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2237     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   2238 
   2239 

IndexError: index out of range in self

**Comment by arnavsinghvi11** [comment] 2024-04-28 18:40
Hi @anushka192001 , 

please refrain from pasting code that has harmful content going forward. I have corrected this on various raised issues by you. 
the issue is still unclear as the stack trace you've pasted does not highlight the impacted DSPy components.  I see that `25 frames` have not been shown. can you please only post the ones related to DSPy?

Closing duplicate issues related to this.

**Closed** 2024-06-24 04:28 UTC
